### ISSUE TITLE
Feature Update of Roland XS-62 Audiometer

### ISSUE THREAD

**Issue by magneriise** [bitfocus/companion-module-roland-xs62s#5]
Because of poor audiometering in the XS62 I want to have a audio meter as a dynamic number value. 

So just a button that show's the current audio level on the assigned channel or master

The codes is described on end of page 28

[XS-62S_reference_v30_eng01_W.pdf](https://github.com/bitfocus/companion/files/5712676/XS-62S_reference_v30_eng01_W.pdf)

Usecase: to do better volum adjustment for audio I/O

**Comment by josephdadams** [comment]
I wrote this module. Based on the protocol, we would have to poll the device for this information in order to store it as a variable. What do you recommend for a polling rate? Or, does it spontaneously return the audio meter information through connected sockets? (The protocol doesn't mention if it does that.)

**Comment by magneriise** [comment]
Hi. 
the polling rate should be as high as possible. Though maybe have a average that updates 3-5 times pr second. I have no idea if this is close to possible?

**Comment by josephdadams** [comment]
I suppose it would depend on how it impacts performance.

**Comment by josephdadams** [comment]
@magneriise I am looking for freelance work, so if you would like to place a bounty on this, let me know.
